# Generated by Django 5.0.1 on 2024-01-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_demo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demo',
            new_name='User',
        ),
    ]
