# Generated by Django 5.0.1 on 2024-01-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_profilephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
