# Generated by Django 5.0.1 on 2024-01-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAuthorized',
            field=models.BooleanField(default=False),
        ),
    ]
