# Generated by Django 5.0.1 on 2024-01-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_isauthorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
