# Generated by Django 5.0.1 on 2024-01-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_user_isauthorized_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='nulll', max_length=20),
            preserve_default=False,
        ),
    ]
