# Generated by Django 5.0.1 on 2024-02-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('date', models.TimeField()),
                ('attendance', models.BooleanField(default=False)),
            ],
        ),
    ]
