# Generated by Django 5.0.1 on 2024-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user_id',
            field=models.CharField(default='false', max_length=50),
            preserve_default=False,
        ),
    ]
