# Generated by Django 5.0.1 on 2024-02-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_attendance_date_remove_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
