# Generated by Django 5.0.1 on 2024-02-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_attendance_date_alter_attendance_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
