# Generated by Django 5.0.1 on 2024-02-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='companyCode',
            field=models.CharField(default='123456', max_length=20),
            preserve_default=False,
        ),
    ]
