# Generated by Django 5.0.1 on 2024-02-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
