# Generated by Django 5.0.1 on 2024-02-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_leave_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
