# Generated by Django 5.0.1 on 2024-02-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='onLeave',
            field=models.BooleanField(default=False),
        ),
    ]
