# Generated by Django 5.0.1 on 2024-02-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='companyCode',
            field=models.CharField(default='123456', max_length=100),
        ),
    ]
