# Generated by Django 5.0.2 on 2024-02-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='dates',
            field=models.DateField(),
        ),
    ]
