# Generated by Django 5.0.2 on 2024-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_holiday_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='dates',
            field=models.CharField(max_length=1000),
        ),
    ]
