# Generated by Django 5.0.2 on 2024-03-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_attendance_isholiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
