# Generated by Django 5.0.2 on 2024-03-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('entry', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('attendance', models.BooleanField(default=False)),
                ('companyCode', models.CharField(max_length=20)),
                ('onLeave', models.BooleanField(default=False)),
                ('isHoliday', models.BooleanField(default=False)),
            ],
        ),
    ]
